[acton]

[acton.2150i]
doc = "Monochromator from Princeton Instruments."

[adafruit]

[adafruit.2348]
doc = "Rasperry Pi hat capable of driving up to 4 DC or 2 Stepper motors with full PWM speed control."
links.manufacturer = "https://www.adafruit.com/product/2348"

[brooks]

[brooks.mfc-gf]
doc = "Thermal Mass Flow Controllers"
links.manufacturer = "https://brooksinstrument.com/en/products/mass-flow-controllers/metal-sealed/gf100-series"

[dwyer]

[dwyer.16b]
doc = "Temperature controller."
links.manufacturer = "https://www.dwyer-inst.com/Product/Temperature/ProcessControllers/Series16B"

[dwyer.16c]
doc = "Temperature controller."
links.manufacturer = "https://www.dwyer-inst.com/Product/Temperature/ProcessControllers/Series16C"

[ealing]

[ealing.37-1070-000]
doc = "50 mm Linear Actuator, With Encoder."
links.manufacturer = "https://www.ealingcatalog.com/50-mm-encoderdrivertm-oem-actuators.html"

[edaq]

[edaq.epu452]
doc = "Four channel multifunction isoPod with USB."
links.manufacturer = "https://www.edaq.com/EPU452"

[gage]

[gage.cse8442]
doc = "Four channel PCIe digitizer card."
links.manufacturer = "http://www.gage-applied.com/digitizers/16-bit/pcie/digitizer-compuscope-octave-express-84xx.htm"

[horiba]

[horiba.microhr]
doc = "Short Focal Length Imaging Spectrometer."
links.manufacturer = "https://www.horiba.com/en_en/products/detail/action/show/Product/microhr-series-1591/"

[labjack]

[labjack.t7-pro]
doc = "Multifunction data acquisition device."
links.manufacturer = "https://labjack.com/products/t7"

[lightcon]

[lightcon.topas-800]
doc = "Optical Parametric Amplifier."
links.manufacturer = "http://lightcon.com/Product/TOPAS-800.html"

[lightcon.topas-c]
doc = "Optical Parametric Amplifier."
links.manufacturer = "http://lightcon.com/Products/opa-topas.html"

[mccdaq]

[mccdaq.mcc118]
doc = "Voltage Measurement DAQ HAT for Raspberry Pi"
links.manufacturer = "https://www.mccdaq.com/DAQ-HAT/MCC-118.aspx"

[mccdaq.mcc152]
doc = "Voltage Output and DIO HAT for Raspberry Pi"
links.manufaturer = "https://www.mccdaq.com/DAQ-HAT/MCC-152.aspx"

[microchip]

[microchip.mcp3428]
doc = "Four channel low-noise, high accuracy delta-sigma A/D converter with differential inputs and up to 16 bits of resolution"
links.manufacturer = "https://www.microchip.com/wwwproducts/en/MCP3428"

[microchip.mcp9600]
doc = "Integrated thermocouple Electromotive Force (EMF) to degree Celsius converter with integrated Cold-Junction compensation"
links.manufacturer = "https://www.microchip.com/wwwproducts/en/MCP9600"

[new-era]

[new-era.ne1000]
doc = "Programmable Single Syringe Pump."
links.manufacturer = "https://www.syringepump.com/NE-1000.php"

[new-era.dualne1000]
doc = "Continuous infusion syringe pump system."
links.manufacturer = "https://www.syringepump.com/continuous.php"

[newport]

[newport.conex-ag-pr100p]
doc = "Piezo motor rotary stage with direct encoder feedback and closed-loop piezo motor controller/driver."
links.manufacturer = "https://www.newport.com/p/CONEX-AG-PR100P"

[newport.mfa-cc]
doc = "Motorized Linear Stage, Miniature, 25 mm Travel, DC Motor, M2 and M3."
links.manufacturer = "https://www.newport.com/p/MFA-CC"

[newport.smc100cc]
doc = "Motion Controller, Single-axis DC Motor."
links.manufacturer = "https://www.newport.com/p/SMC100CC"

[newport.smc100pp]
doc = "Motion Controller, Single-axis Stepper Motor."
links.manufacturer = "https://www.newport.com/p/SMC100PP"

[ni]

[ni.pci-6251]
doc = "PCI Multifunction I/O Device 'DAQ'."
links.manufacturer = "https://www.ni.com/en-us/support/model.pci-6251.html"

[ocean-insight]

[ocean-insight.usb2000]
doc = "Fiber optic spectrometer."
links.manufacturer = "https://www.oceaninsight.com/products/spectrometers/usb-series/usb-uv-nir/"

[ocean-insight.usb4000]
doc = "Fiber optic spectrometer."
links.manufacturer = "https://www.oceaninsight.com/products/spectrometers/usb-series/usb-uv-nir/"

[pmc]
doc = "Precision MicroControl Corporation (PMC) designs and manufactures high-performance multi-axis motion controllers for servo and stepper motor control."
links.homepage = "https://pmccorp.com/"

[pmc.dcx-pci100]
doc = "1 to 8 axis PCI-bus motion controller which can control and drive up to eight small DC servo motors without the need for external amplifiers."
links.manufacturer = "https://pmccorp.com/products/dcxpci.php#pci100"

[rasperry-pi]

[raspberry-pi."3b+"]
doc = "Rasperry Pi 3 Model B+."
links.manufacturer = "https://www.raspberrypi.org/products/raspberry-pi-3-model-b-plus/"

[raspberry-pi.4b]
doc = "Rasperry Pi 4 Model B."
links.manufacturer = "https://www.raspberrypi.org/products/raspberry-pi-4-model-b/"

[rgb-photonics]

[rgb-photonics.qmini]
doc = "Minature USB spectrometer for UV-VIS-NIR measurments"
links.manufacturer = "https://www.broadcom.com/products/optical-sensors/spectrometers/spectrometers-qmini"

[rigol]

[rigol.mso1104]
doc = "Rigol oscilloscope with built-in function generator."
links.manufacturer = "https://www.rigolna.com/products/digital-oscilloscopes/1000z/"

[thorlabs]

[thorlabs.bsc201]
doc = "One-channel benchtop stepper motor controller."
links.manufacturer = "https://www.thorlabs.com/thorproduct.cfm?partnumber=BSC201"

[thorlabs.bsc203]
doc = "Three-channel benchtop stepper motor controller."
links.manufacturer = "https://www.thorlabs.com/thorproduct.cfm?partnumber=BSC203"

[thorlabs.ell18]
doc = "Rotation stage."
links.manufacturer = "https://www.thorlabs.com/thorproduct.cfm?partnumber=ELL18"

[thorlabs.ell18m]
doc = "Rotation stage."
links.manufacturer = "https://www.thorlabs.com/thorproduct.cfm?partnumber=ELL18/M"

[thorlabs.kdc101]
doc = "K-Cube brushed DC servo motor controller."
links.manufacturer = "https://www.thorlabs.com/thorproduct.cfm?partnumber=KDC101"

[thorlabs.kst101]
doc = "K-Cube stepper motor controller."
links.manufacturer = "https://www.thorlabs.com/thorproduct.cfm?partnumber=KST101"

[thorlabs.k10cr1]
doc = "Motorized rotation mount, stepper motor."
links.manufacturer = "https://www.thorlabs.com/thorproduct.cfm?partnumber=K10CR1"

[thorlabs.lnr502]
doc = "TravelMax translation stage."
links.manufacturer = "https://www.thorlabs.com/thorproduct.cfm?partnumber=LNR502"

[thorlabs.lts150]
doc = "150 mm Linear Translation Stage with Integrated Controller, Stepper Motor."
links.manufacturer = "https://www.thorlabs.com/newgrouppage9.cfm?objectgroup_id=7652&pn=LTS150"

[thorlabs.lts300]
doc = "300 mm Linear Translation Stage with Integrated Controller, Stepper Motor."
links.manufacturer = "https://www.thorlabs.com/newgrouppage9.cfm?objectgroup_id=7652&pn=LTS300"

[thorlabs.mpc320]
doc = "Motorized Fiber Polarization Controller."
links.manufacturer = "https://www.thorlabs.com/thorproduct.cfm?partnumber=MPC320"

[thorlabs.pax1000ir1]
doc = "Infrared polarimeter."
links.manufacturer = "https://www.thorlabs.com/thorproduct.cfm?partnumber=PAX1000IR1"

[thorlabs.pm100d]
doc = "Digital optical power and energy meter."
links.manufacturer = "https://www.thorlabs.com/thorproduct.cfm?partnumber=PM100D"

[ti]
doc = "Texas Instruments Incorporated"
links.homepage = "https://www.ti.com/"

[ti.ads1115]
doc = "16-Bit 860SPS 4-Ch Delta-Sigma ADC With PGA, Oscillator, Vref, Comparator, and I2C."
links.manufacturer = "http://www.ti.com/product/ADS1115"

[vici]

[vici.e2ca]
doc = "Two-position microelectric valve actuator."
links.manufacturer = "https://www.vici.com/act/mic.php"

[vici.edma]
doc = "Two-position injectors / switching valves."
links.manufacturer = "https://www.vici.com/vval/hplc_semi_16-75.php"

