[clients]

[clients.yaqc-bluesky]
badges = [
  "<a href='https://github.com/bluesky/yaqc-bluesky'><img alt='CI' src='https://img.shields.io/github/checks-status/bluesky/yaqc-bluesky/master'></a>",
  "<a href='https://pypi.org/project/yaqc-bluesky'><img src='https://img.shields.io/pypi/v/yaqc-bluesky'></a>",
  "<a href='https://anaconda.org/conda-forge/yaqc-bluesky'><img src='https://img.shields.io/conda/vn/conda-forge/yaqc-bluesky'></a>",
]

[clients.yaqc-cmds]
badges = [
  "<a href='https://github.com/wright-group/yaqc-cmds'><img alt='CI' src='https://img.shields.io/github/checks-status/wright-group/yaqc-cmds/master'></a>",
  "<a href='https://pypi.org/project/yaqc-cmds'><img src='https://img.shields.io/pypi/v/yaqc-cmds'></a>",
]

[clients.yaqc-python]
badges = [
  "<a href='https://github.com/yaq-project/yaq-python'><img src='https://img.shields.io/github/checks-status/yaq-project/yaq-python/main'></a>",
  "<a href='https://pypi.org/project/yaqc'><img src='https://img.shields.io/pypi/v/yaqc'></a>",
  "<a href='https://anaconda.org/conda-forge/yaqc'><img src='https://img.shields.io/conda/vn/conda-forge/yaqc'></a>",
]

[clients.yaqc-qtpy]
badges = [
  "<a href='https://github.com/yaq-project/yaqc-qtpy'><img src='https://img.shields.io/github/checks-status/yaq-project/yaqc-qtpy/main'></a>",
  "<a href='https://pypi.org/project/yaqc-qtpy'><img src='https://img.shields.io/pypi/v/yaqc-qtpy'></a>",
  "<a href='https://anaconda.org/conda-forge/yaqc-qtpy'><img src='https://img.shields.io/conda/vn/conda-forge/yaqc-qtpy'></a>",
]

[daemons]

[daemons.yaqd-acton]
badges = [
  "<a href='https://github.com/yaq-project/yaqd-acton'><img src='https://img.shields.io/github/checks-status/yaq-project/yaqd-acton/main'></a>",
  "<a href='https://pypi.org/project/yaqd-acton'><img src='https://img.shields.io/pypi/v/yaqd-acton'></a>",
  "<a href='https://anaconda.org/conda-forge/yaqd-acton'><img src='https://img.shields.io/conda/vn/conda-forge/yaqd-acton'></a>",
]

[daemons.yaqd-adafruit]
badges = [
  "<a href='https://github.com/yaq-project/yaqd-adafruit'><img src='https://img.shields.io/github/checks-status/yaq-project/yaqd-adafruit/main'></a>",
  "<a href='https://pypi.org/project/yaqd-adafruit'><img src='https://img.shields.io/pypi/v/yaqd-adafruit'></a>",
]

[daemons.yaqd-andor]
badges = [
  "<a href='https://github.com/yaq-project/yaqd-andor'><img src='https://img.shields.io/github/checks-status/yaq-project/yaqd-andor/main'></a>",
  "<a href='https://pypi.org/project/yaqd-andor'><img src='https://img.shields.io/pypi/v/yaqd-andor'></a>",
  "<a href='https://anaconda.org/conda-forge/yaqd-andor'><img src='https://img.shields.io/conda/vn/conda-forge/yaqd-andor'></a>",
]

[daemons.yaqd-attune]
badges = [
  "<a href='https://github.com/yaq-project/yaqd-attune'><img src='https://img.shields.io/github/checks-status/yaq-project/yaqd-attune/main'></a>",
  "<a href='https://pypi.org/project/yaqd-attune'><img src='https://img.shields.io/pypi/v/yaqd-attune'></a>",
  "<a href='https://anaconda.org/conda-forge/yaqd-attune'><img src='https://img.shields.io/conda/vn/conda-forge/yaqd-attune'></a>",
]

[daemons.yaqd-becker-hickl]
badges = [
  "<a href='https://github.com/yaq-project/yaqd-becker-hickl'><img src='https://img.shields.io/github/checks-status/yaq-project/yaqd-becker-hickl/main'></a>",
  "<a href='https://pypi.org/project/yaqd-becker-hickl'><img src='https://img.shields.io/pypi/v/yaqd-becker-hickl'></a>",
  "<a href='https://anaconda.org/conda-forge/yaqd-becker-hickl'><img src='https://img.shields.io/conda/vn/conda-forge/yaqd-becker-hickl'></a>",
]

[daemons.yaqd-brooks]
badges = [
  "<a href='https://github.com/yaq-project/yaqd-brooks'><img src='https://img.shields.io/github/checks-status/yaq-project/yaqd-brooks/main'></a>",
  "<a href='https://pypi.org/project/yaqd-brooks'><img src='https://img.shields.io/pypi/v/yaqd-brooks'></a>",
  "<a href='https://anaconda.org/conda-forge/yaqd-brooks'><img src='https://img.shields.io/conda/vn/conda-forge/yaqd-brooks'></a>",
]

[daemons.yaqd-core-python]
badges = [
  "<a href='https://github.com/yaq-project/yaq-python'><img src='https://img.shields.io/github/checks-status/yaq-project/yaq-python/main'></a>",
  "<a href='https://pypi.org/project/yaqd-core'><img src='https://img.shields.io/pypi/v/yaqd-core'></a>",
  "<a href='https://anaconda.org/conda-forge/yaqd-core'><img src='https://img.shields.io/conda/vn/conda-forge/yaqd-core'></a>",
]

[daemons.yaqd-dwyer]
badges = [
  "<a href='https://github.com/yaq-project/yaqd-dwyer'><img alt='CI' src='https://img.shields.io/github/checks-status/yaq-project/yaqd-dwyer/main'></a>",
  "<a href='https://pypi.org/project/yaqd-dwyer'><img src='https://img.shields.io/pypi/v/yaqd-dwyer'></a>",
  "<a href='https://anaconda.org/conda-forge/yaqd-dwyer'><img src='https://img.shields.io/conda/vn/conda-forge/yaqd-dwyer'></a>",
]

[daemons.yaqd-edaq]
badges = [
  "<a href='https://github.com/yaq-project/yaqd-edaq'><img src='https://img.shields.io/github/checks-status/yaq-project/yaqd-edaq/main'></a>",
  "<a href='https://pypi.org/project/yaqd-edaq'><img src='https://img.shields.io/pypi/v/yaqd-edaq'></a>",
  "<a href='https://anaconda.org/conda-forge/yaqd-edaq'><img src='https://img.shields.io/conda/vn/conda-forge/yaqd-edaq'></a>",
]

[daemons.yaqd-ekspla]
badges = [
  "<a href='https://github.com/yaq-project/yaqd-ekspla'><img src='https://img.shields.io/github/checks-status/yaq-project/yaqd-ekspla/main'></a>",
  "<a href='https://pypi.org/project/yaqd-ekspla'><img src='https://img.shields.io/pypi/v/yaqd-ekspla'></a>",
  "<a href='https://anaconda.org/conda-forge/yaqd-ekspla'><img src='https://img.shields.io/conda/vn/conda-forge/yaqd-ekspla'></a>",
]

[daemons.yaqd-fakes]
badges = [
  "<a href='https://github.com/yaq-project/yaq-python'><img src='https://img.shields.io/github/checks-status/yaq-project/yaq-python/main'></a>",
  "<a href='https://pypi.org/project/yaqd-fakes'><img src='https://img.shields.io/pypi/v/yaqd-fakes'></a>",
  "<a href='https://anaconda.org/conda-forge/yaqd-fakes'><img src='https://img.shields.io/conda/vn/conda-forge/yaqd-fakes'></a>",
]

[daemons.yaqd-gage]
badges = [
  "<a href='https://github.com/yaq-project/yaqd-gage'><img src='https://img.shields.io/github/checks-status/yaq-project/yaqd-gage/main'></a>",
  "<a href='https://pypi.org/project/yaqd-gage'><img src='https://img.shields.io/pypi/v/yaqd-gage'></a>",
  "<a href='https://anaconda.org/conda-forge/yaqd-gage'><img src='https://img.shields.io/conda/vn/conda-forge/yaqd-gage'></a>",
]


[daemons.yaqd-gdrive]
badges = [
  "<a href='https://github.com/yaq-project/yaqd-gdrive'><img src='https://img.shields.io/github/checks-status/yaq-project/yaqd-gdrive/main'></a>",
  "<a href='https://pypi.org/project/yaqd-gdrive'><img src='https://img.shields.io/pypi/v/yaqd-gdrive'></a>",
  "<a href='https://anaconda.org/conda-forge/yaqd-gdrive'><img src='https://img.shields.io/conda/vn/conda-forge/yaqd-gdrive'></a>",
]

[daemons.yaqd-horiba]
badges = [
  "<a href='https://github.com/yaq-project/yaqd-horiba'><img src='https://img.shields.io/github/checks-status/yaq-project/yaqd-horiba/main'></a>",
  "<a href='https://pypi.org/project/yaqd-horiba'><img src='https://img.shields.io/pypi/v/yaqd-horiba'></a>",
  "<a href='https://anaconda.org/conda-forge/yaqd-horiba'><img src='https://img.shields.io/conda/vn/conda-forge/yaqd-horiba'></a>",
]

[daemons.yaqd-labjack]
badges = [
  "<a href='https://github.com/yaq-project/yaqd-labjack/actions'><img src='https://img.shields.io/github/checks-status/yaq-project/yaqd-labjack/main'></a>",
  "<a href='https://pypi.org/project/yaqd-labjack'><img src='https://img.shields.io/pypi/v/yaqd-labjack'></a>",
  "<a href='https://anaconda.org/conda-forge/yaqd-labjack'><img src='https://img.shields.io/conda/vn/conda-forge/yaqd-labjack'></a>",
]

[daemons.yaqd-lightcon]
badges = [
  "<a href='https://github.com/yaq-project/yaqd-lightcon'><img src='https://img.shields.io/github/checks-status/yaq-project/yaqd-lightcon/main'></a>",
  "<a href='https://pypi.org/project/yaqd-lightcon'><img src='https://img.shields.io/pypi/v/yaqd-lightcon'></a>",
  "<a href='https://anaconda.org/conda-forge/yaqd-lightcon'><img src='https://img.shields.io/conda/vn/conda-forge/yaqd-lightcon'></a>",
]

[daemons.yaqd-mcc]
badges = [
  "<a href='https://github.com/yaq-project/yaqd-mcc'><img src='https://img.shields.io/github/checks-status/yaq-project/yaqd-mcc/main'></a>",
  "<a href='https://pypi.org/project/yaqd-mcc'><img src='https://img.shields.io/pypi/v/yaqd-mcc'></a>",
]

[daemons.yaqd-microchip]
badges = [
  "<a href='https://github.com/yaq-project/yaqd-microchip'><img src='https://img.shields.io/github/checks-status/yaq-project/yaqd-microchip/main'></a>",
  "<a href='https://pypi.org/project/yaqd-microchip'><img src='https://img.shields.io/pypi/v/yaqd-microchip'></a>",
  "<a href='https://anaconda.org/conda-forge/yaqd-microchip'><img src='https://img.shields.io/conda/vn/conda-forge/yaqd-microchip'></a>",
]

[daemons.yaqd-mqtt]
badges = [
  "<a href='https://github.com/yaq-project/yaqd-mqtt'><img src='https://img.shields.io/github/checks-status/yaq-project/yaqd-mqtt/main'></a>",
  "<a href='https://pypi.org/project/yaqd-mqtt'><img src='https://img.shields.io/pypi/v/yaqd-mqtt'></a>",
  "<a href='https://anaconda.org/conda-forge/yaqd-mqtt'><img src='https://img.shields.io/conda/vn/conda-forge/yaqd-mqtt'></a>",
]

[daemons.yaqd-new-era]
badges = [
  "<a href='https://github.com/yaq-project/yaqd-new-era'><img src='https://img.shields.io/github/checks-status/yaq-project/yaqd-new-era/main'></a>",
  "<a href='https://pypi.org/project/yaqd-new-era'><img src='https://img.shields.io/pypi/v/yaqd-new-era'></a>",
  "<a href='https://anaconda.org/conda-forge/yaqd-new-era'><img src='https://img.shields.io/conda/vn/conda-forge/yaqd-new-era'></a>",
]

[daemons.yaqd-newport]
badges = [
  "<a href='https://github.com/yaq-project/yaqd-newport'><img src='https://img.shields.io/github/checks-status/yaq-project/yaqd-newport/main'></a>",
  "<a href='https://pypi.org/project/yaqd-newport'><img src='https://img.shields.io/pypi/v/yaqd-newport'></a>",
  "<a href='https://anaconda.org/conda-forge/yaqd-newport'><img src='https://img.shields.io/conda/vn/conda-forge/yaqd-newport'></a>",
]

[daemons.yaqd-ni]
badges = [
  "<a href='https://github.com/yaq-project/yaqd-ni'><img src='https://img.shields.io/github/checks-status/yaq-project/yaqd-ni/main'></a>",
  "<a href='https://pypi.org/project/yaqd-ni'><img src='https://img.shields.io/pypi/v/yaqd-ni'></a>",
  "<a href='https://anaconda.org/conda-forge/yaqd-ni'><img src='https://img.shields.io/conda/vn/conda-forge/yaqd-ni'></a>",
]

[daemons.yaqd-picotech]
badges = [
  "<a href='https://github.com/yaq-project/yaqd-picotech'><img src='https://img.shields.io/github/checks-status/yaq-project/yaqd-picotech/main'></a>",
  "<a href='https://pypi.org/project/yaqd-picotech'><img src='https://img.shields.io/pypi/v/yaqd-picotech'></a>",
  "<a href='https://anaconda.org/conda-forge/yaqd-picotech'><img src='https://img.shields.io/conda/vn/conda-forge/yaqd-picotech'></a>",
]

[daemons.yaqd-pmc]
badges = [
  "<a href='https://github.com/yaq-project/yaqd-pmc'><img src='https://img.shields.io/github/checks-status/yaq-project/yaqd-pmc/main'></a>",
  "<a href='https://pypi.org/project/yaqd-pmc'><img src='https://img.shields.io/pypi/v/yaqd-pmc'></a>",
  "<a href='https://anaconda.org/conda-forge/yaqd-pmc'><img src='https://img.shields.io/conda/vn/conda-forge/yaqd-pmc'></a>",
]

[daemons.yaqd-rpi-gpio]
badges = [
  "<a href='https://github.com/yaq-project/yaqd-rpi-gpio'><img src='https://img.shields.io/github/checks-status/yaq-project/yaqd-rpi-gpio/main'></a>",
  "<a href='https://pypi.org/project/yaqd-rpi-gpio'><img src='https://img.shields.io/pypi/v/yaqd-rpi-gpio'></a>",
]

[daemons.yaqd-rgb]
badges = [
  "<a href='https://github.com/yaq-project/yaqd-rgb'><img src='https://img.shields.io/github/checks-status/yaq-project/yaqd-rgb/main'></a>",
  "<a href='https://pypi.org/project/yaqd-rgb'><img src='https://img.shields.io/pypi/v/yaqd-rgb'></a>",
  "<a href='https://anaconda.org/conda-forge/yaqd-rgb'><img src='https://img.shields.io/conda/vn/conda-forge/yaqd-rgb'></a>",
]


[daemons.yaqd-scpi]
badges = [
  "<a href='https://github.com/yaq-project/yaqd-scpi'><img src='https://img.shields.io/github/checks-status/yaq-project/yaqd-scpi/main'></a>",
  "<a href='https://pypi.org/project/yaqd-scpi'><img src='https://img.shields.io/pypi/v/yaqd-scpi'></a>",
  "<a href='https://anaconda.org/conda-forge/yaqd-scpi'><img src='https://img.shields.io/conda/vn/conda-forge/yaqd-scpi'></a>",
]

[daemons.yaqd-seabreeze]
badges = [
  "<a href='https://github.com/yaq-project/yaqd-seabreeze'><img src='https://img.shields.io/github/checks-status/yaq-project/yaqd-seabreeze/main'></a>",
  "<a href='https://pypi.org/project/yaqd-seabreeze'><img src='https://img.shields.io/pypi/v/yaqd-seabreeze'></a>",
  "<a href='https://anaconda.org/conda-forge/yaqd-seabreeze'><img src='https://img.shields.io/conda/vn/conda-forge/yaqd-seabreeze'></a>",
]

[daemons.yaqd-system-monitor]
badges = [
  "<a href='https://github.com/yaq-project/yaqd-system-monitor'><img src='https://img.shields.io/github/checks-status/yaq-project/yaqd-system-monitor/main'></a>",
  "<a href='https://pypi.org/project/yaqd-system-monitor'><img src='https://img.shields.io/pypi/v/yaqd-system-monitor'></a>",
  "<a href='https://anaconda.org/conda-forge/yaqd-system-monitor'><img src='https://img.shields.io/conda/vn/conda-forge/yaqd-system-monitor'></a>",
]

[daemons.yaqd-ti]
badges = [
  "<a href='https://github.com/yaq-project/yaqd-ti'><img src='https://img.shields.io/github/checks-status/yaq-project/yaqd-ti/main'></a>",
  "<a href='https://pypi.org/project/yaqd-ti'><img src='https://img.shields.io/pypi/v/yaqd-ti'></a>",
  "<a href='https://anaconda.org/conda-forge/yaqd-ti'><img src='https://img.shields.io/conda/vn/conda-forge/yaqd-ti'></a>",
]

[daemons.yaqd-thorlabs]
badges = [
  "<a href='https://github.com/yaq-project/yaqd-thorlabs'><img src='https://img.shields.io/github/checks-status/yaq-project/yaqd-thorlabs/main'></a>",
  "<a href='https://pypi.org/project/yaqd-thorlabs'><img src='https://img.shields.io/pypi/v/yaqd-thorlabs'></a>",
  "<a href='https://anaconda.org/conda-forge/yaqd-thorlabs'><img src='https://img.shields.io/conda/vn/conda-forge/yaqd-thorlabs'></a>",
]

[daemons.yaqd-vici]
badges = [
  "<a href='https://github.com/yaq-project/yaqd-vici'><img src='https://img.shields.io/github/checks-status/yaq-project/yaqd-vici/main'></a>",
  "<a href='https://pypi.org/project/yaqd-vici'><img src='https://img.shields.io/pypi/v/yaqd-vici'></a>",
  "<a href='https://anaconda.org/conda-forge/yaqd-vici'><img src='https://img.shields.io/conda/vn/conda-forge/yaqd-vici'></a>",
]


[daemons.yaqd-wright]
badges = [
  "<a href='https://github.com/wright-group/yaqd-wright'><img src='https://img.shields.io/github/checks-status/wright-group/yaqd-wright/main'></a>",
  "<a href='https://pypi.org/project/yaqd-wright'><img src='https://img.shields.io/pypi/v/yaqd-wright'></a>",
  "<a href='https://anaconda.org/conda-forge/yaqd-wright'><img src='https://img.shields.io/conda/vn/conda-forge/yaqd-wright'></a>",
]

[daemons.yaqd-zaber]
badges = [
  "<a href='https://github.com/yaq-project/yaqd-zaber'><img src='https://img.shields.io/github/checks-status/yaq-project/yaqd-zaber/main'></a>",
  "<a href='https://pypi.org/project/yaqd-zaber'><img src='https://img.shields.io/pypi/v/yaqd-zaber'></a>",
  "<a href='https://anaconda.org/conda-forge/yaqd-zaber'><img src='https://img.shields.io/conda/vn/conda-forge/yaqd-zaber'></a>",
]

[documentation]

[documentation.python-yaq-fyi]
badges = [
  "<a href='https://github.com/yaq-project/python-yaq-fyi'><img src='https://img.shields.io/github/checks-status/yaq-project/python-yaq-fyi/main'></a>",
]

[documentation.yeps]
badges = [
  "<a href='https://github.com/yaq-project/yeps'><img src='https://img.shields.io/github/checks-status/yaq-project/yeps/main'></a>",
]

[documentation.yaq-fyi]
badges = [
  "<a href='https://github.com/yaq-project/yaq-fyi'><img src='https://img.shields.io/github/checks-status/yaq-project/yaq-fyi/main'></a>",
]

[tooling]

[tooling.hart-protocol]
badges = [
  "<a href='https://github.com/yaq-project/hart-protocol'><img src='https://img.shields.io/github/checks-status/yaq-project/hart-protocol/main'></a>",
  "<a href='https://pypi.org/project/hart-protocol'><img src='https://img.shields.io/pypi/v/hart-protocol'></a>",
  "<a href='https://anaconda.org/conda-forge/hart-protocol'><img src='https://img.shields.io/conda/vn/conda-forge/hart-protocol'></a>",
]

[tooling.qtypes]
badges = [
  "<a href='https://github.com/yaq-project/qtypes'><img src='https://img.shields.io/github/checks-status/yaq-project/qtypes/main'></a>",
  "<a href='https://pypi.org/project/qtypes'><img src='https://img.shields.io/pypi/v/qtypes'></a>",
  "<a href='https://anaconda.org/conda-forge/qtypes'><img src='https://img.shields.io/conda/vn/conda-forge/qtypes'></a>",
]

[tooling.thorlabs-apt-protocol]
badges = [
  "<a href='https://github.com/yaq-project/thorlabs-apt-protocol'><img src='https://img.shields.io/github/checks-status/yaq-project/thorlabs-apt-protocol/main'></a>",
  "<a href='https://pypi.org/project/thorlabs-apt-protocol'><img src='https://img.shields.io/pypi/v/thorlabs-apt-protocol'></a>",
  "<a href='https://anaconda.org/conda-forge/thorlabs-apt-protocol'><img src='https://img.shields.io/conda/vn/conda-forge/thorlabs-apt-protocol'></a>",
]

[tooling.yaq-traits]
badges = [
  "<a href='https://github.com/yaq-project/yaq-traits'><img src='https://img.shields.io/github/checks-status/yaq-project/yaq-traits/main'></a>",
  "<a href='https://pypi.org/project/yaq-traits'><img src='https://img.shields.io/pypi/v/yaq-traits'></a>",
  "<a href='https://anaconda.org/conda-forge/yaq-traits'><img src='https://img.shields.io/conda/vn/conda-forge/yaq-traits'></a>",
]

[tooling.yaqd-control]
badges = [
  "<a href='https://github.com/yaq-project/yaqd-control'><img src='https://img.shields.io/github/checks-status/yaq-project/yaqd-control/main'></a>",
  "<a href='https://pypi.org/project/yaqd-control'><img src='https://img.shields.io/pypi/v/yaqd-control'></a>",
  "<a href='https://anaconda.org/conda-forge/yaqd-control'><img src='https://img.shields.io/conda/vn/conda-forge/yaqd-control'></a>",
]
