name = "system-monitor"
description = "Sensor daemon to monitor local system performance (CPU, memory, uptime, and disk)."
traits = ["is-sensor", "is-daemon"]

[links]
source = "https://gitlab.com/yaq/yaqd-system-monitor"
bugtracker = "https://gitlab.com/yaq/yaqd-system-monitor/-/issues"

[installation]
PyPI = "https://pypi.org/project/yaqd-system-monitor/"