trait = "is-sensor"
doc = """
Daemons with the is-sensor trait are capable of measuring some unknown quantities.
Sensor daemons may have multiple channels if a single measurement returns multiple values.
"""
requires = []

[messages]

[messages.get_measured]
doc = "Get most recent measured value."

[messages.get_measured.response]
type = "map"
values = ["float", "ndarray"]

[messages.get_channel_names]
doc = "Get current channel names."
response.type = "array"
response.items = "string"

[messages.get_channel_shapes]
doc = "Get current channel shapes. If list is empty, channel is scalar."
response.type = "map"
response.values = {"type"="array", "items"="int"}

[messages.get_channel_units]
doc = "Get current channel units."
response.type = "map"
response.values = ["null", "string"]
